version: '3'

services:
  dm-nginx:
    image: nginx:latest
    container_name: ${RECORD_SET_NAME:-dm}-nginx
    volumes:
      - ./dm-nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./dm-nginx/error.html:/usr/share/nginx/html/error.html
    ports:
      - 1235:80
    restart: always
    depends_on:
      - dm-record-manager
      - dm-record-manager-server
      - dm-s-pipes-engine
      - dm-rdf4j
  dm-record-manager:
    image: 'docker.pkg.github.com/blcham/record-manager/record-manager:latest'
    container_name: ${RECORD_SET_NAME:-dm}-record-manager
    ports:
      - '4000:80'
    restart: always
    depends_on:
      - dm-record-manager-server
    environment:
      API_URL: "${RECORD_MANAGER_SERVER_URL}"
      APP_TITLE: "${RECORD_MANAGER_APP_TITLE:-Record manager}"
      LANGUAGE: "${LANGUAGE:-en}"
      NAVIGATOR_LANGUAGE: "false"
      BASENAME: "${RECORD_MANAGER_BASENAME:-/record-manager}"

  dm-record-manager-server:
    image: 'docker.pkg.github.com/blcham/record-manager/record-manager-server:latest'
    container_name: ${RECORD_SET_NAME:-dm}-record-manager-server
    ports:
      - '3000:8080'
    restart: always
    depends_on:
      - dm-s-pipes-engine
      - dm-rdf4j
    environment:
      repositoryUrl: "http://dm-rdf4j:8080/rdf4j-server/repositories/record-manager-app"
      formGenRepositoryUrl: "http://dm-rdf4j:8080/rdf4j-server/repositories/record-manager-formgen"
      formGenServiceUrl: "${FORMGEN_SERVICE_URL}"
    volumes:
      - ./logs/dm-record-manager-server:/usr/local/tomcat/logs

  dm-s-pipes-engine:
    image: 'docker.pkg.github.com/blcham/vfn-model/vita-s-pipes-engine:latest'
    #image: 'vita-s-pipes-engine:latest'
    container_name: ${RECORD_SET_NAME:-dm}-s-pipes-engine
    ports:
      - "8889:8080"
    restart: always
    depends_on:
      - dm-rdf4j
    environment:
      FORMGEN_REPOSITORY_URL: "http://dm-rdf4j:8080/rdf4j-server/repositories/record-manager-formgen"
    volumes:
      - ./logs/dm-s-pipes-engine:/usr/local/tomcat/logs

  dm-rdf4j:
    image: 'eclipse/rdf4j-workbench:amd64-3.5.0'
    container_name: ${RECORD_SET_NAME:-dm}-rdf4j
    ports:
      - "8888:8080"
    restart: always
    environment:
      - JAVA_OPTS=-Xms1g -Xmx4g
    volumes:
      - data:/var/rdf4j
      - ./logs/dm-rdf4j:/usr/local/tomcat/logs

volumes:
  data:
  logs:
