version: '3'

services:
  dm-record-manager:
    image: 'docker.pkg.github.com/opendata-mvcr/ofn-record-manager/ofn-record-manager:latest'
    container_name: dm-record-manager
    ports:
      - '4000:80'
    depends_on:
      - dm-record-manager-server
    environment:
      API_URL: "${RECORD_MANAGER_SERVER_URL}"
      APP_TITLE: "Správce otevřených dat"
      LANGUAGE: "cs"
      NAVIGATOR_LANGUAGE: "false"
      BASENAME: "/ofn-record-manager"

  dm-record-manager-server:
    image: 'docker.pkg.github.com/opendata-mvcr/ofn-record-manager/ofn-record-manager-server:latest'
    container_name: dm-record-manager-server
    ports:
      - '3000:8080'
    depends_on:
      - dm-s-pipes-engine
      - dm-rdf4j
    environment:
      repositoryUrl: "http://dm-rdf4j:8080/rdf4j-server/repositories/ofn-record-manager-app"
      formGenRepositoryUrl: "http://dm-rdf4j:8080/rdf4j-server/repositories/ofn-record-manager-formgen"
      formGenServiceUrl: "${FORMGEN_SERVICE_URL}"

  dm-s-pipes-engine:
    image: 'docker.pkg.github.com/kbss-cvut/s-pipes/s-pipes-engine:latest'
    container_name: dm-s-pipes-engine
    ports:
      - "8889:8080"
    depends_on:
      - dm-rdf4j
    environment:
      - CONTEXTS_SCRIPTPATHS=/scripts
    volumes:
      - ./scripts:/scripts

  dm-rdf4j:
    image: 'eclipse/rdf4j-workbench:amd64-3.5.0'
    container_name: dm-rdf4j
    ports:
      - "8888:8080"
    environment:
      - JAVA_OPTS=-Xms1g -Xmx4g
    volumes:
      - data:/var/rdf4j
      - logs:/usr/local/tomcat/logs

volumes:
  data:
  logs:
